apiVersion: v2
name: ilias
description: A Helm chart for ILIAS LMS
type: application
version: 0.2.0
appVersion: 10
dependencies:
  - name: mariadb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.6.1
    condition: mariadb.enabled